// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vdoc5503_harness.h for the primary calling header

#ifndef VERILATED_VDOC5503_HARNESS___024ROOT_H_
#define VERILATED_VDOC5503_HARNESS___024ROOT_H_  // guard

#include "verilated.h"


class Vdoc5503_harness__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vdoc5503_harness___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(reset_n_i,0,0);
        VL_IN8(clk_en_i,0,0);
        VL_OUT8(irq_n_o,0,0);
        VL_IN8(cs_n_i,0,0);
        VL_IN8(we_n_i,0,0);
        VL_IN8(addr_i,7,0);
        VL_IN8(data_i,7,0);
        VL_OUT8(data_o,7,0);
        VL_OUT8(wave_rd_o,0,0);
        VL_IN8(wave_data_ready_i,0,0);
        VL_IN8(wave_data_i,7,0);
        CData/*7:0*/ doc5503_harness__DOT__osc_int;
        CData/*7:0*/ doc5503_harness__DOT__osc_en;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_int_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__cycle_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__cycle_step_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__cycle_max_w;
        CData/*5:0*/ doc5503_harness__DOT__doc5503_inst__DOT__mixer_cycle_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__last_osc_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__ready_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__init_cycle_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__last_cycle_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__last_cycle_step_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__inhibit_host_writes_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__next_am_req_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__current_wds_reset_req_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__current_osc_halt_req_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__partner_unhalt_req_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__partner_control_load_req_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__next_control_load_req_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__current_acc_add_req_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__current_acc_reset_req_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__partner_acc_reset_req_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__output_reset_req;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__output_update_req;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__prev_cs_n_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__req_cs_w;
        CData/*2:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_state_r;
        CData/*1:0*/ doc5503_harness__DOT__doc5503_inst__DOT__mixer_state_r;
        CData/*3:0*/ doc5503_harness__DOT__doc5503_inst__DOT__mixer_channel_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk1__DOT__data_w;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk1__DOT__vol_s;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk2__DOT__shift_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk3__DOT__overflow;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk3__DOT__zero_byte_w;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk3__DOT__unnamedblk4__DOT__ptr_hi_mask_w;
        CData/*3:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk5__DOT__ca;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_addr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_read_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_read_addr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__data_a_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__data_b_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_ctrl__DOT__found;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_read_ctrl__DOT__found;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__unnamedblk6__DOT__data_curr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT____Vlvbound_hb38b23b0__0;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT____Vlvbound_h3d041937__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT____Vlvbound_hd935d61a__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
    };
    struct {
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_addr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_read_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_read_addr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__data_a_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__data_b_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_ctrl__DOT__found;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_read_ctrl__DOT__found;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__unnamedblk6__DOT__data_curr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT____Vlvbound_hb38b23b0__0;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT____Vlvbound_h3d041937__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT____Vlvbound_hd935d61a__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_addr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_read_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_read_addr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__data_a_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__data_b_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_ctrl__DOT__found;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_ctrl__DOT__unnamedblk1__DOT__unnamedblk2__DOT__inhibit_en;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_read_ctrl__DOT__found;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__unnamedblk6__DOT__data_curr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT____Vlvbound_h3d041937__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT____Vlvbound_hd935d61a__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_addr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_read_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_read_addr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__data_a_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__data_b_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_ctrl__DOT__found;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_ctrl__DOT__unnamedblk1__DOT__unnamedblk2__DOT__inhibit_en;
    };
    struct {
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_read_ctrl__DOT__found;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__unnamedblk6__DOT__data_curr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT____Vlvbound_h3d041937__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT____Vlvbound_hd935d61a__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_addr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_read_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_read_addr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__data_a_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__data_b_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_ctrl__DOT__found;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_read_ctrl__DOT__found;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__unnamedblk6__DOT__data_curr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT____Vlvbound_hb38b23b0__0;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT____Vlvbound_h3d041937__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT____Vlvbound_hd935d61a__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_addr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_read_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_read_addr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__data_a_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__data_b_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_ctrl__DOT__found;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_ctrl__DOT__unnamedblk1__DOT__unnamedblk2__DOT__inhibit_en;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_read_ctrl__DOT__found;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__unnamedblk6__DOT__data_curr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT____Vlvbound_hdf6ad119__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT____Vlvbound_h8a8ade32__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
    };
    struct {
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_port_loop__BRA__3__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__1__KET____DOT__read_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__1__KET____DOT__read_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__1__KET____DOT__read_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__1__KET____DOT__read_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__1__KET____DOT__read_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__2__KET____DOT__read_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__2__KET____DOT__read_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__2__KET____DOT__read_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__2__KET____DOT__read_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__2__KET____DOT__read_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_addr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_read_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_read_addr_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__data_a_r;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__data_b_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_ctrl__DOT__found;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_read_ctrl__DOT__found;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__unnamedblk6__DOT__data_curr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT____Vlvbound_hb38b23b0__0;
        CData/*7:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT____Vlvbound_h3d041937__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT____Vlvbound_hd935d61a__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__gen_read_ports__DOT__priority_read_port_loop__BRA__0__KET____DOT__read_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_addr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_ctrl__DOT__found;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT____Vlvbound_h8dbb67ef__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__0__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
    };
    struct {
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_en_r;
        CData/*4:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_addr_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_ctrl__DOT__found;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT____Vlvbound_h8dbb67ef__0;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__1__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_s_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__prev_r_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__q_r;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_s_w;
        CData/*0:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_port_loop__BRA__2__KET____DOT__gen_edge_triggered__DOT__write_ff__DOT__edge_r_w;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__reset_n_i__0;
        CData/*0:0*/ __VactContinue;
        VL_OUT16(wave_address_o,15,0);
        VL_OUT16(mono_mix_o,15,0);
        VL_OUT16(left_mix_o,15,0);
        VL_OUT16(right_mix_o,15,0);
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__wave_addr_r;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__output_r;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__mono_mix_r;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__next_mono_mix_r;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__left_mix_r;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__next_left_mix_r;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__right_mix_r;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__next_right_mix_r;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk3__DOT__unnamedblk4__DOT__ptr_w;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk3__DOT__unnamedblk4__DOT__addr_w;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__data_a_r;
        SData/*15:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__data_b_r;
        IData/*31:0*/ doc5503_harness__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__unnamedblk3__DOT__high_bit_w;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_read_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_read_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_read_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_read_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_read_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_index;
    };
    struct {
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_read_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_read_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__unnamedblk6__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_index;
        IData/*23:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__data_a_r;
        IData/*23:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__data_b_r;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__unnamedblk6__DOT__i;
        IData/*23:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__unnamedblk6__DOT__data_curr_r;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_index;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__unnamedblk4__DOT__i;
        IData/*31:0*/ doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__unnamedblk5__DOT__i;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__freq_low;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__freq_high;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__volume;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__data_sample;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__addr_pointer;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__control;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__resolution_table_size;
        VlUnpacked<SData/*15:0*/, 16> doc5503_harness__DOT__doc5503_inst__DOT__channel_o;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellout__osc_fl_r_inst__priority_read_data_o;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fl_r_inst__priority_read_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fl_r_inst__priority_read_req_i;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fl_r_inst__priority_write_data_i;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fl_r_inst__priority_write_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fl_r_inst__priority_write_req_i;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellout__osc_fh_r_inst__priority_read_data_o;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fh_r_inst__priority_read_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fh_r_inst__priority_read_req_i;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fh_r_inst__priority_write_data_i;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fh_r_inst__priority_write_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_fh_r_inst__priority_write_req_i;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellout__osc_vol_r_inst__priority_read_data_o;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_vol_r_inst__priority_read_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_vol_r_inst__priority_read_req_i;
        VlUnpacked<CData/*7:0*/, 2> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_vol_r_inst__priority_write_data_i;
        VlUnpacked<CData/*4:0*/, 2> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_vol_r_inst__priority_write_addr_i;
        VlUnpacked<CData/*0:0*/, 2> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_vol_r_inst__priority_write_req_i;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellout__osc_wds_r_inst__priority_read_data_o;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wds_r_inst__priority_read_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wds_r_inst__priority_read_req_i;
        VlUnpacked<CData/*7:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wds_r_inst__priority_write_data_i;
        VlUnpacked<CData/*4:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wds_r_inst__priority_write_addr_i;
        VlUnpacked<CData/*0:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wds_r_inst__priority_write_req_i;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellout__osc_wtp_r_inst__priority_read_data_o;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wtp_r_inst__priority_read_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wtp_r_inst__priority_read_req_i;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wtp_r_inst__priority_write_data_i;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wtp_r_inst__priority_write_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_wtp_r_inst__priority_write_req_i;
        VlUnpacked<CData/*7:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT____Vcellout__osc_control_r_inst__priority_read_data_o;
        VlUnpacked<CData/*4:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_control_r_inst__priority_read_addr_i;
        VlUnpacked<CData/*0:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_control_r_inst__priority_read_req_i;
        VlUnpacked<CData/*7:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_control_r_inst__priority_write_data_i;
        VlUnpacked<CData/*4:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_control_r_inst__priority_write_addr_i;
        VlUnpacked<CData/*0:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_control_r_inst__priority_write_req_i;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellout__osc_rts_r_inst__priority_read_data_o;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_rts_r_inst__priority_read_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_rts_r_inst__priority_read_req_i;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_rts_r_inst__priority_write_data_i;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_rts_r_inst__priority_write_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_rts_r_inst__priority_write_req_i;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_acc_r_inst__priority_read_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_acc_r_inst__priority_read_req_i;
        VlUnpacked<IData/*23:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_acc_r_inst__priority_write_data_i;
        VlUnpacked<CData/*4:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_acc_r_inst__priority_write_addr_i;
        VlUnpacked<CData/*0:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_acc_r_inst__priority_write_req_i;
        VlUnpacked<CData/*4:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_output_r_inst__priority_read_addr_i;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_output_r_inst__priority_read_req_i;
        VlUnpacked<SData/*15:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_output_r_inst__priority_write_data_i;
        VlUnpacked<CData/*4:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_output_r_inst__priority_write_addr_i;
        VlUnpacked<CData/*0:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT____Vcellinp__osc_output_r_inst__priority_write_req_i;
        VlUnpacked<SData/*15:0*/, 16> doc5503_harness__DOT__doc5503_inst__DOT__channel_r;
        VlUnpacked<SData/*15:0*/, 16> doc5503_harness__DOT__doc5503_inst__DOT__next_channel_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_write_ack_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_read_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_read_ack_r;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__priority_read_data_r;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__doc5503_inst__DOT__osc_fl_r_inst__DOT__data_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_write_ack_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_read_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_read_ack_r;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__priority_read_data_r;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__doc5503_inst__DOT__osc_fh_r_inst__DOT__data_r;
        VlUnpacked<CData/*0:0*/, 2> doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_w;
        VlUnpacked<CData/*0:0*/, 2> doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_write_ack_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_read_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_read_ack_r;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__priority_read_data_r;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__doc5503_inst__DOT__osc_vol_r_inst__DOT__data_r;
        VlUnpacked<CData/*0:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_w;
        VlUnpacked<CData/*0:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_write_ack_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_read_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_read_ack_r;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__priority_read_data_r;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__doc5503_inst__DOT__osc_wds_r_inst__DOT__data_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_write_ack_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_read_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_read_ack_r;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__priority_read_data_r;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__doc5503_inst__DOT__osc_wtp_r_inst__DOT__data_r;
        VlUnpacked<CData/*0:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_w;
        VlUnpacked<CData/*0:0*/, 4> doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_write_ack_r;
        VlUnpacked<CData/*0:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_read_w;
        VlUnpacked<CData/*0:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_read_ack_r;
        VlUnpacked<CData/*7:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__priority_read_data_r;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__doc5503_inst__DOT__osc_control_r_inst__DOT__data_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_write_ack_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_read_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_read_ack_r;
        VlUnpacked<CData/*7:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__priority_read_data_r;
        VlUnpacked<CData/*7:0*/, 32> doc5503_harness__DOT__doc5503_inst__DOT__osc_rts_r_inst__DOT__data_r;
        VlUnpacked<IData/*23:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_read_data_o;
        VlUnpacked<CData/*0:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_w;
        VlUnpacked<CData/*0:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_write_ack_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_read_w;
    };
    struct {
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_read_ack_r;
        VlUnpacked<IData/*23:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__priority_read_data_r;
        VlUnpacked<IData/*23:0*/, 32> doc5503_harness__DOT__doc5503_inst__DOT__osc_acc_r_inst__DOT__data_r;
        VlUnpacked<SData/*15:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_read_data_o;
        VlUnpacked<CData/*0:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_w;
        VlUnpacked<CData/*0:0*/, 3> doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_write_ack_r;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_read_w;
        VlUnpacked<CData/*0:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_read_ack_r;
        VlUnpacked<SData/*15:0*/, 1> doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__priority_read_data_r;
        VlUnpacked<SData/*15:0*/, 32> doc5503_harness__DOT__doc5503_inst__DOT__osc_output_r_inst__DOT__data_r;
        VlUnpacked<CData/*0:0*/, 4> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vdoc5503_harness__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vdoc5503_harness___024root(Vdoc5503_harness__Syms* symsp, const char* v__name);
    ~Vdoc5503_harness___024root();
    VL_UNCOPYABLE(Vdoc5503_harness___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
