// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vdoc5503_verilog_test__Syms.h"


void Vdoc5503_verilog_test___024root__trace_chg_0_sub_0(Vdoc5503_verilog_test___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vdoc5503_verilog_test___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_chg_0\n"); );
    // Init
    Vdoc5503_verilog_test___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vdoc5503_verilog_test___024root*>(voidSelf);
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vdoc5503_verilog_test___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vdoc5503_verilog_test___024root__trace_chg_0_sub_0(Vdoc5503_verilog_test___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_chg_0_sub_0\n"); );
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    if (VL_UNLIKELY(((vlSelfRef.__Vm_traceActivity[1U] 
                      | vlSelfRef.__Vm_traceActivity
                      [2U])))) {
        bufp->chgBit(oldp+0,(vlSelfRef.doc5503_verilog_test__DOT__reset_n));
        bufp->chgBit(oldp+1,(vlSelfRef.doc5503_verilog_test__DOT__cs_n));
        bufp->chgBit(oldp+2,(vlSelfRef.doc5503_verilog_test__DOT__we_n));
        bufp->chgCData(oldp+3,(vlSelfRef.doc5503_verilog_test__DOT__addr),8);
        bufp->chgCData(oldp+4,(vlSelfRef.doc5503_verilog_test__DOT__data_in),8);
    }
    if (VL_UNLIKELY((vlSelfRef.__Vm_traceActivity[3U]))) {
        bufp->chgCData(oldp+5,(vlSelfRef.doc5503_verilog_test__DOT__data_out),8);
        bufp->chgSData(oldp+6,(vlSelfRef.doc5503_verilog_test__DOT__wave_address),16);
        bufp->chgBit(oldp+7,(vlSelfRef.doc5503_verilog_test__DOT__wave_rd));
        bufp->chgSData(oldp+8,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__mono_mix_r),16);
        bufp->chgSData(oldp+9,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__left_mix_r),16);
        bufp->chgSData(oldp+10,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__right_mix_r),16);
        bufp->chgBit(oldp+11,((0U != (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__cycle_state_r))));
        bufp->chgCData(oldp+12,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_en_r),8);
        bufp->chgSData(oldp+13,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[0]),16);
        bufp->chgSData(oldp+14,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[1]),16);
        bufp->chgSData(oldp+15,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[2]),16);
        bufp->chgSData(oldp+16,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[3]),16);
        bufp->chgSData(oldp+17,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[4]),16);
        bufp->chgSData(oldp+18,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[5]),16);
        bufp->chgSData(oldp+19,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[6]),16);
        bufp->chgSData(oldp+20,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[7]),16);
        bufp->chgSData(oldp+21,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[8]),16);
        bufp->chgSData(oldp+22,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[9]),16);
        bufp->chgSData(oldp+23,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[10]),16);
        bufp->chgSData(oldp+24,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[11]),16);
        bufp->chgSData(oldp+25,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[12]),16);
        bufp->chgSData(oldp+26,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[13]),16);
        bufp->chgSData(oldp+27,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[14]),16);
        bufp->chgSData(oldp+28,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[15]),16);
        bufp->chgCData(oldp+29,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[0]),2);
        bufp->chgCData(oldp+30,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[1]),2);
        bufp->chgCData(oldp+31,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[2]),2);
        bufp->chgCData(oldp+32,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[3]),2);
        bufp->chgCData(oldp+33,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[4]),2);
        bufp->chgCData(oldp+34,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[5]),2);
        bufp->chgCData(oldp+35,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[6]),2);
        bufp->chgCData(oldp+36,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[7]),2);
        bufp->chgCData(oldp+37,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_halt_r),8);
        bufp->chgCData(oldp+38,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_addr_r),8);
        bufp->chgCData(oldp+39,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_data_r),8);
        bufp->chgBit(oldp+40,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_we_n_r));
        bufp->chgBit(oldp+41,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_cs_n_r));
        bufp->chgBit(oldp+42,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_we_n_r));
        bufp->chgBit(oldp+43,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_access_r));
        bufp->chgCData(oldp+44,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_int_r),8);
        bufp->chgCData(oldp+45,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[0]),2);
        bufp->chgCData(oldp+46,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[1]),2);
        bufp->chgCData(oldp+47,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[2]),2);
        bufp->chgCData(oldp+48,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[3]),2);
        bufp->chgCData(oldp+49,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[4]),2);
        bufp->chgCData(oldp+50,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[5]),2);
        bufp->chgCData(oldp+51,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[6]),2);
        bufp->chgCData(oldp+52,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[7]),2);
        bufp->chgCData(oldp+53,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fl_osc_r),5);
        bufp->chgCData(oldp+54,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fh_osc_r),5);
        bufp->chgCData(oldp+55,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_vol_osc_r),5);
        bufp->chgCData(oldp+56,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wds_osc_r),5);
        bufp->chgCData(oldp+57,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wtp_osc_r),5);
        bufp->chgCData(oldp+58,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_control_osc_r),5);
        bufp->chgCData(oldp+59,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_rts_osc_r),5);
        bufp->chgCData(oldp+60,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_acc_osc_r),5);
        bufp->chgBit(oldp+61,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fl_we_r));
        bufp->chgBit(oldp+62,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fh_we_r));
        bufp->chgBit(oldp+63,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_vol_we_r));
        bufp->chgBit(oldp+64,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wds_we_r));
        bufp->chgBit(oldp+65,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wtp_we_r));
        bufp->chgBit(oldp+66,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_control_we_r));
        bufp->chgBit(oldp+67,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_rts_we_r));
        bufp->chgBit(oldp+68,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_acc_we_r));
        bufp->chgCData(oldp+69,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fl_din_r),8);
        bufp->chgCData(oldp+70,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fh_din_r),8);
        bufp->chgCData(oldp+71,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_vol_din_r),8);
        bufp->chgCData(oldp+72,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wds_din_r),8);
        bufp->chgCData(oldp+73,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wtp_din_r),8);
        bufp->chgCData(oldp+74,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_control_din_r),8);
        bufp->chgCData(oldp+75,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_rts_din_r),8);
        bufp->chgIData(oldp+76,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_acc_din_r),24);
        bufp->chgCData(oldp+77,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fl_dout_w),8);
        bufp->chgCData(oldp+78,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fh_dout_w),8);
        bufp->chgCData(oldp+79,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_vol_dout_w),8);
        bufp->chgCData(oldp+80,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wds_dout_w),8);
        bufp->chgCData(oldp+81,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wtp_dout_w),8);
        bufp->chgCData(oldp+82,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_control_dout_w),8);
        bufp->chgCData(oldp+83,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_rts_dout_w),8);
        bufp->chgIData(oldp+84,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r
                                [vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_acc_osc_r]),24);
        bufp->chgCData(oldp+85,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_fl_r),8);
        bufp->chgCData(oldp+86,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_fh_r),8);
        bufp->chgCData(oldp+87,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_vol_r),8);
        bufp->chgCData(oldp+88,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_wds_r),8);
        bufp->chgCData(oldp+89,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_wtp_r),8);
        bufp->chgCData(oldp+90,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_control_r),8);
        bufp->chgCData(oldp+91,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r),8);
        bufp->chgCData(oldp+92,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__partner_control_r),8);
        bufp->chgCData(oldp+93,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_control_r),8);
        bufp->chgCData(oldp+94,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_control_r),8);
        bufp->chgBit(oldp+95,((0U == (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_wds_r))));
        bufp->chgCData(oldp+96,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_osc_r),5);
        bufp->chgBit(oldp+97,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_osc_r))));
        bufp->chgBit(oldp+98,((1U & (~ (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_osc_r)))));
        bufp->chgCData(oldp+99,((1U ^ (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_osc_r))),5);
        bufp->chgCData(oldp+100,((7U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r) 
                                        >> 3U))),3);
        bufp->chgCData(oldp+101,((7U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r))),3);
        bufp->chgCData(oldp+102,((0x1fU & (((IData)(9U) 
                                            + (7U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r))) 
                                           - (7U & 
                                              ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r) 
                                               >> 3U))))),5);
        bufp->chgBit(oldp+103,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_control_r))));
        bufp->chgCData(oldp+104,((3U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_control_r) 
                                        >> 1U))),2);
        bufp->chgCData(oldp+105,((0xfU & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_control_r) 
                                          >> 4U))),4);
        bufp->chgBit(oldp+106,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__partner_control_r))));
        bufp->chgCData(oldp+107,((3U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__partner_control_r) 
                                        >> 1U))),2);
        bufp->chgBit(oldp+108,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_control_r))));
        bufp->chgCData(oldp+109,((3U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_control_r) 
                                        >> 1U))),2);
        bufp->chgBit(oldp+110,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_control_r))));
        bufp->chgCData(oldp+111,((3U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_control_r) 
                                        >> 1U))),2);
        bufp->chgIData(oldp+112,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_acc_r),24);
        bufp->chgIData(oldp+113,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_output_r),18);
        bufp->chgCData(oldp+114,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__loaded_wds_r),8);
        bufp->chgSData(oldp+115,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[0]),16);
        bufp->chgSData(oldp+116,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[1]),16);
        bufp->chgSData(oldp+117,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[2]),16);
        bufp->chgSData(oldp+118,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[3]),16);
        bufp->chgSData(oldp+119,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[4]),16);
        bufp->chgSData(oldp+120,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[5]),16);
        bufp->chgSData(oldp+121,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[6]),16);
        bufp->chgSData(oldp+122,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[7]),16);
        bufp->chgSData(oldp+123,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[8]),16);
        bufp->chgSData(oldp+124,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[9]),16);
        bufp->chgSData(oldp+125,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[10]),16);
        bufp->chgSData(oldp+126,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[11]),16);
        bufp->chgSData(oldp+127,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[12]),16);
        bufp->chgSData(oldp+128,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[13]),16);
        bufp->chgSData(oldp+129,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[14]),16);
        bufp->chgSData(oldp+130,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[15]),16);
        bufp->chgIData(oldp+131,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[0]),24);
        bufp->chgIData(oldp+132,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[1]),24);
        bufp->chgIData(oldp+133,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[2]),24);
        bufp->chgIData(oldp+134,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[3]),24);
        bufp->chgIData(oldp+135,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[4]),24);
        bufp->chgIData(oldp+136,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[5]),24);
        bufp->chgIData(oldp+137,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[6]),24);
        bufp->chgIData(oldp+138,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[7]),24);
        bufp->chgIData(oldp+139,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[8]),24);
        bufp->chgIData(oldp+140,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[9]),24);
        bufp->chgIData(oldp+141,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[10]),24);
        bufp->chgIData(oldp+142,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[11]),24);
        bufp->chgIData(oldp+143,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[12]),24);
        bufp->chgIData(oldp+144,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[13]),24);
        bufp->chgIData(oldp+145,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[14]),24);
        bufp->chgIData(oldp+146,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[15]),24);
        bufp->chgIData(oldp+147,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_sum_r),24);
        bufp->chgIData(oldp+148,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_mono_mix_r),24);
        bufp->chgIData(oldp+149,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_left_mix_r),24);
        bufp->chgIData(oldp+150,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_right_mix_r),24);
        bufp->chgCData(oldp+151,((0x1fU & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_en_r) 
                                           >> 1U))),5);
        bufp->chgCData(oldp+152,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__cycle_timer_r),6);
        bufp->chgCData(oldp+153,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__cycle_state_r),2);
        bufp->chgBit(oldp+154,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__cycle_start_r));
        bufp->chgCData(oldp+155,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__clk_count_r),3);
        bufp->chgCData(oldp+156,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_state_r),4);
        bufp->chgBit(oldp+157,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__loaded_wds_pending_r));
        bufp->chgBit(oldp+158,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__halt_zero_r));
        bufp->chgBit(oldp+159,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_request_pending_r));
        bufp->chgBit(oldp+160,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__device_response_pending_r));
        bufp->chgIData(oldp+161,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[0]),24);
        bufp->chgIData(oldp+162,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[1]),24);
        bufp->chgIData(oldp+163,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[2]),24);
        bufp->chgIData(oldp+164,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[3]),24);
        bufp->chgIData(oldp+165,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[4]),24);
        bufp->chgIData(oldp+166,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[5]),24);
        bufp->chgIData(oldp+167,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[6]),24);
        bufp->chgIData(oldp+168,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[7]),24);
        bufp->chgIData(oldp+169,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[8]),24);
        bufp->chgIData(oldp+170,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[9]),24);
        bufp->chgIData(oldp+171,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[10]),24);
        bufp->chgIData(oldp+172,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[11]),24);
        bufp->chgIData(oldp+173,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[12]),24);
        bufp->chgIData(oldp+174,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[13]),24);
        bufp->chgIData(oldp+175,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[14]),24);
        bufp->chgIData(oldp+176,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[15]),24);
        bufp->chgIData(oldp+177,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[16]),24);
        bufp->chgIData(oldp+178,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[17]),24);
        bufp->chgIData(oldp+179,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[18]),24);
        bufp->chgIData(oldp+180,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[19]),24);
        bufp->chgIData(oldp+181,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[20]),24);
        bufp->chgIData(oldp+182,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[21]),24);
        bufp->chgIData(oldp+183,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[22]),24);
        bufp->chgIData(oldp+184,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[23]),24);
        bufp->chgIData(oldp+185,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[24]),24);
        bufp->chgIData(oldp+186,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[25]),24);
        bufp->chgIData(oldp+187,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[26]),24);
        bufp->chgIData(oldp+188,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[27]),24);
        bufp->chgIData(oldp+189,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[28]),24);
        bufp->chgIData(oldp+190,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[29]),24);
        bufp->chgIData(oldp+191,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[30]),24);
        bufp->chgIData(oldp+192,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[31]),24);
        bufp->chgCData(oldp+193,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[0]),8);
        bufp->chgCData(oldp+194,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[1]),8);
        bufp->chgCData(oldp+195,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[2]),8);
        bufp->chgCData(oldp+196,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[3]),8);
        bufp->chgCData(oldp+197,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[4]),8);
        bufp->chgCData(oldp+198,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[5]),8);
        bufp->chgCData(oldp+199,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[6]),8);
        bufp->chgCData(oldp+200,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[7]),8);
        bufp->chgCData(oldp+201,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[8]),8);
        bufp->chgCData(oldp+202,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[9]),8);
        bufp->chgCData(oldp+203,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[10]),8);
        bufp->chgCData(oldp+204,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[11]),8);
        bufp->chgCData(oldp+205,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[12]),8);
        bufp->chgCData(oldp+206,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[13]),8);
        bufp->chgCData(oldp+207,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[14]),8);
        bufp->chgCData(oldp+208,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[15]),8);
        bufp->chgCData(oldp+209,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[16]),8);
        bufp->chgCData(oldp+210,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[17]),8);
        bufp->chgCData(oldp+211,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[18]),8);
        bufp->chgCData(oldp+212,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[19]),8);
        bufp->chgCData(oldp+213,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[20]),8);
        bufp->chgCData(oldp+214,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[21]),8);
        bufp->chgCData(oldp+215,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[22]),8);
        bufp->chgCData(oldp+216,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[23]),8);
        bufp->chgCData(oldp+217,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[24]),8);
        bufp->chgCData(oldp+218,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[25]),8);
        bufp->chgCData(oldp+219,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[26]),8);
        bufp->chgCData(oldp+220,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[27]),8);
        bufp->chgCData(oldp+221,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[28]),8);
        bufp->chgCData(oldp+222,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[29]),8);
        bufp->chgCData(oldp+223,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[30]),8);
        bufp->chgCData(oldp+224,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[31]),8);
        bufp->chgCData(oldp+225,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[0]),8);
        bufp->chgCData(oldp+226,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[1]),8);
        bufp->chgCData(oldp+227,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[2]),8);
        bufp->chgCData(oldp+228,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[3]),8);
        bufp->chgCData(oldp+229,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[4]),8);
        bufp->chgCData(oldp+230,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[5]),8);
        bufp->chgCData(oldp+231,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[6]),8);
        bufp->chgCData(oldp+232,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[7]),8);
        bufp->chgCData(oldp+233,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[8]),8);
        bufp->chgCData(oldp+234,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[9]),8);
        bufp->chgCData(oldp+235,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[10]),8);
        bufp->chgCData(oldp+236,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[11]),8);
        bufp->chgCData(oldp+237,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[12]),8);
        bufp->chgCData(oldp+238,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[13]),8);
        bufp->chgCData(oldp+239,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[14]),8);
        bufp->chgCData(oldp+240,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[15]),8);
        bufp->chgCData(oldp+241,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[16]),8);
        bufp->chgCData(oldp+242,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[17]),8);
        bufp->chgCData(oldp+243,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[18]),8);
        bufp->chgCData(oldp+244,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[19]),8);
        bufp->chgCData(oldp+245,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[20]),8);
        bufp->chgCData(oldp+246,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[21]),8);
        bufp->chgCData(oldp+247,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[22]),8);
        bufp->chgCData(oldp+248,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[23]),8);
        bufp->chgCData(oldp+249,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[24]),8);
        bufp->chgCData(oldp+250,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[25]),8);
        bufp->chgCData(oldp+251,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[26]),8);
        bufp->chgCData(oldp+252,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[27]),8);
        bufp->chgCData(oldp+253,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[28]),8);
        bufp->chgCData(oldp+254,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[29]),8);
        bufp->chgCData(oldp+255,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[30]),8);
        bufp->chgCData(oldp+256,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[31]),8);
        bufp->chgCData(oldp+257,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[0]),8);
        bufp->chgCData(oldp+258,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[1]),8);
        bufp->chgCData(oldp+259,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[2]),8);
        bufp->chgCData(oldp+260,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[3]),8);
        bufp->chgCData(oldp+261,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[4]),8);
        bufp->chgCData(oldp+262,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[5]),8);
        bufp->chgCData(oldp+263,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[6]),8);
        bufp->chgCData(oldp+264,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[7]),8);
        bufp->chgCData(oldp+265,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[8]),8);
        bufp->chgCData(oldp+266,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[9]),8);
        bufp->chgCData(oldp+267,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[10]),8);
        bufp->chgCData(oldp+268,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[11]),8);
        bufp->chgCData(oldp+269,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[12]),8);
        bufp->chgCData(oldp+270,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[13]),8);
        bufp->chgCData(oldp+271,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[14]),8);
        bufp->chgCData(oldp+272,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[15]),8);
        bufp->chgCData(oldp+273,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[16]),8);
        bufp->chgCData(oldp+274,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[17]),8);
        bufp->chgCData(oldp+275,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[18]),8);
        bufp->chgCData(oldp+276,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[19]),8);
        bufp->chgCData(oldp+277,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[20]),8);
        bufp->chgCData(oldp+278,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[21]),8);
        bufp->chgCData(oldp+279,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[22]),8);
        bufp->chgCData(oldp+280,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[23]),8);
        bufp->chgCData(oldp+281,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[24]),8);
        bufp->chgCData(oldp+282,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[25]),8);
        bufp->chgCData(oldp+283,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[26]),8);
        bufp->chgCData(oldp+284,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[27]),8);
        bufp->chgCData(oldp+285,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[28]),8);
        bufp->chgCData(oldp+286,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[29]),8);
        bufp->chgCData(oldp+287,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[30]),8);
        bufp->chgCData(oldp+288,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[31]),8);
        bufp->chgCData(oldp+289,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[0]),8);
        bufp->chgCData(oldp+290,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[1]),8);
        bufp->chgCData(oldp+291,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[2]),8);
        bufp->chgCData(oldp+292,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[3]),8);
        bufp->chgCData(oldp+293,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[4]),8);
        bufp->chgCData(oldp+294,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[5]),8);
        bufp->chgCData(oldp+295,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[6]),8);
        bufp->chgCData(oldp+296,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[7]),8);
        bufp->chgCData(oldp+297,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[8]),8);
        bufp->chgCData(oldp+298,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[9]),8);
        bufp->chgCData(oldp+299,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[10]),8);
        bufp->chgCData(oldp+300,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[11]),8);
        bufp->chgCData(oldp+301,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[12]),8);
        bufp->chgCData(oldp+302,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[13]),8);
        bufp->chgCData(oldp+303,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[14]),8);
        bufp->chgCData(oldp+304,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[15]),8);
        bufp->chgCData(oldp+305,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[16]),8);
        bufp->chgCData(oldp+306,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[17]),8);
        bufp->chgCData(oldp+307,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[18]),8);
        bufp->chgCData(oldp+308,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[19]),8);
        bufp->chgCData(oldp+309,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[20]),8);
        bufp->chgCData(oldp+310,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[21]),8);
        bufp->chgCData(oldp+311,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[22]),8);
        bufp->chgCData(oldp+312,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[23]),8);
        bufp->chgCData(oldp+313,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[24]),8);
        bufp->chgCData(oldp+314,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[25]),8);
        bufp->chgCData(oldp+315,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[26]),8);
        bufp->chgCData(oldp+316,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[27]),8);
        bufp->chgCData(oldp+317,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[28]),8);
        bufp->chgCData(oldp+318,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[29]),8);
        bufp->chgCData(oldp+319,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[30]),8);
        bufp->chgCData(oldp+320,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[31]),8);
        bufp->chgCData(oldp+321,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[0]),8);
        bufp->chgCData(oldp+322,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[1]),8);
        bufp->chgCData(oldp+323,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[2]),8);
        bufp->chgCData(oldp+324,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[3]),8);
        bufp->chgCData(oldp+325,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[4]),8);
        bufp->chgCData(oldp+326,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[5]),8);
        bufp->chgCData(oldp+327,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[6]),8);
        bufp->chgCData(oldp+328,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[7]),8);
        bufp->chgCData(oldp+329,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[8]),8);
        bufp->chgCData(oldp+330,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[9]),8);
        bufp->chgCData(oldp+331,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[10]),8);
        bufp->chgCData(oldp+332,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[11]),8);
        bufp->chgCData(oldp+333,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[12]),8);
        bufp->chgCData(oldp+334,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[13]),8);
        bufp->chgCData(oldp+335,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[14]),8);
        bufp->chgCData(oldp+336,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[15]),8);
        bufp->chgCData(oldp+337,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[16]),8);
        bufp->chgCData(oldp+338,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[17]),8);
        bufp->chgCData(oldp+339,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[18]),8);
        bufp->chgCData(oldp+340,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[19]),8);
        bufp->chgCData(oldp+341,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[20]),8);
        bufp->chgCData(oldp+342,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[21]),8);
        bufp->chgCData(oldp+343,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[22]),8);
        bufp->chgCData(oldp+344,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[23]),8);
        bufp->chgCData(oldp+345,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[24]),8);
        bufp->chgCData(oldp+346,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[25]),8);
        bufp->chgCData(oldp+347,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[26]),8);
        bufp->chgCData(oldp+348,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[27]),8);
        bufp->chgCData(oldp+349,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[28]),8);
        bufp->chgCData(oldp+350,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[29]),8);
        bufp->chgCData(oldp+351,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[30]),8);
        bufp->chgCData(oldp+352,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[31]),8);
        bufp->chgCData(oldp+353,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[0]),8);
        bufp->chgCData(oldp+354,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[1]),8);
        bufp->chgCData(oldp+355,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[2]),8);
        bufp->chgCData(oldp+356,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[3]),8);
        bufp->chgCData(oldp+357,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[4]),8);
        bufp->chgCData(oldp+358,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[5]),8);
        bufp->chgCData(oldp+359,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[6]),8);
        bufp->chgCData(oldp+360,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[7]),8);
        bufp->chgCData(oldp+361,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[8]),8);
        bufp->chgCData(oldp+362,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[9]),8);
        bufp->chgCData(oldp+363,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[10]),8);
        bufp->chgCData(oldp+364,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[11]),8);
        bufp->chgCData(oldp+365,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[12]),8);
        bufp->chgCData(oldp+366,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[13]),8);
        bufp->chgCData(oldp+367,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[14]),8);
        bufp->chgCData(oldp+368,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[15]),8);
        bufp->chgCData(oldp+369,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[16]),8);
        bufp->chgCData(oldp+370,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[17]),8);
        bufp->chgCData(oldp+371,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[18]),8);
        bufp->chgCData(oldp+372,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[19]),8);
        bufp->chgCData(oldp+373,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[20]),8);
        bufp->chgCData(oldp+374,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[21]),8);
        bufp->chgCData(oldp+375,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[22]),8);
        bufp->chgCData(oldp+376,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[23]),8);
        bufp->chgCData(oldp+377,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[24]),8);
        bufp->chgCData(oldp+378,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[25]),8);
        bufp->chgCData(oldp+379,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[26]),8);
        bufp->chgCData(oldp+380,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[27]),8);
        bufp->chgCData(oldp+381,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[28]),8);
        bufp->chgCData(oldp+382,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[29]),8);
        bufp->chgCData(oldp+383,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[30]),8);
        bufp->chgCData(oldp+384,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[31]),8);
        bufp->chgCData(oldp+385,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[0]),8);
        bufp->chgCData(oldp+386,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[1]),8);
        bufp->chgCData(oldp+387,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[2]),8);
        bufp->chgCData(oldp+388,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[3]),8);
        bufp->chgCData(oldp+389,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[4]),8);
        bufp->chgCData(oldp+390,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[5]),8);
        bufp->chgCData(oldp+391,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[6]),8);
        bufp->chgCData(oldp+392,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[7]),8);
        bufp->chgCData(oldp+393,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[8]),8);
        bufp->chgCData(oldp+394,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[9]),8);
        bufp->chgCData(oldp+395,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[10]),8);
        bufp->chgCData(oldp+396,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[11]),8);
        bufp->chgCData(oldp+397,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[12]),8);
        bufp->chgCData(oldp+398,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[13]),8);
        bufp->chgCData(oldp+399,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[14]),8);
        bufp->chgCData(oldp+400,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[15]),8);
        bufp->chgCData(oldp+401,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[16]),8);
        bufp->chgCData(oldp+402,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[17]),8);
        bufp->chgCData(oldp+403,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[18]),8);
        bufp->chgCData(oldp+404,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[19]),8);
        bufp->chgCData(oldp+405,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[20]),8);
        bufp->chgCData(oldp+406,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[21]),8);
        bufp->chgCData(oldp+407,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[22]),8);
        bufp->chgCData(oldp+408,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[23]),8);
        bufp->chgCData(oldp+409,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[24]),8);
        bufp->chgCData(oldp+410,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[25]),8);
        bufp->chgCData(oldp+411,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[26]),8);
        bufp->chgCData(oldp+412,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[27]),8);
        bufp->chgCData(oldp+413,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[28]),8);
        bufp->chgCData(oldp+414,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[29]),8);
        bufp->chgCData(oldp+415,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[30]),8);
        bufp->chgCData(oldp+416,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[31]),8);
    }
    bufp->chgBit(oldp+417,(vlSelfRef.doc5503_verilog_test__DOT__clk));
    bufp->chgBit(oldp+418,((0U == (7U & vlSelfRef.doc5503_verilog_test__DOT__cycle_count))));
    bufp->chgBit(oldp+419,(vlSelfRef.doc5503_verilog_test__DOT__wave_data_ready));
    bufp->chgCData(oldp+420,(vlSelfRef.doc5503_verilog_test__DOT__wave_data),8);
    bufp->chgIData(oldp+421,(vlSelfRef.doc5503_verilog_test__DOT__cycle_count),32);
}

void Vdoc5503_verilog_test___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_cleanup\n"); );
    // Init
    Vdoc5503_verilog_test___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vdoc5503_verilog_test___024root*>(voidSelf);
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    vlSymsp->__Vm_activity = false;
    vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
    vlSymsp->TOP.__Vm_traceActivity[3U] = 0U;
}
