// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vdoc5503_verilog_test__Syms.h"


VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_init_sub__TOP__0(Vdoc5503_verilog_test___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_init_sub__TOP__0\n"); );
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushPrefix("doc5503_verilog_test", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+418,0,"clk",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+1,0,"reset_n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+419,0,"clk_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"cs_n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"we_n",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+4,0,"addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+5,0,"data_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+6,0,"data_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+7,0,"wave_address",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+8,0,"wave_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+420,0,"wave_data_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+421,0,"wave_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+9,0,"mono_mix",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+10,0,"left_mix",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+11,0,"right_mix",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+12,0,"ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+13,0,"osc_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+422,0,"cycle_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("dut", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+423,0,"CLOCK_SPEED_HZ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+424,0,"DOC_CLOCK_SPEED_HZ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+418,0,"clk_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+1,0,"reset_n_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+419,0,"clk_en_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"cs_n_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"we_n_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+4,0,"addr_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+5,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+6,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+7,0,"wave_address_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+8,0,"wave_rd_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+420,0,"wave_data_ready_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+421,0,"wave_data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+9,0,"mono_mix_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+10,0,"left_mix_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+11,0,"right_mix_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("channel_o", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+14+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->declBit(c+12,0,"ready_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+13,0,"osc_en_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("osc_mode_o", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 8; ++i) {
        tracep->declBus(c+30+i*1,0,"",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, true,(i+0), 1,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+38,0,"osc_halt_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+39,0,"host_addr_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+40,0,"host_data_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+41,0,"host_we_n_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+42,0,"prev_cs_n_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+43,0,"prev_we_n_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+44,0,"host_access_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+45,0,"osc_int_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+13,0,"osc_en_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("osc_mode_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 8; ++i) {
        tracep->declBus(c+46+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 1,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+38,0,"osc_halt_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+54,0,"ram_fl_osc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+55,0,"ram_fh_osc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+56,0,"ram_vol_osc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+57,0,"ram_wds_osc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+58,0,"ram_wtp_osc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+59,0,"ram_control_osc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+60,0,"ram_rts_osc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+61,0,"ram_acc_osc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+62,0,"ram_fl_we_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+63,0,"ram_fh_we_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+64,0,"ram_vol_we_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+65,0,"ram_wds_we_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+66,0,"ram_wtp_we_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+67,0,"ram_control_we_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+68,0,"ram_rts_we_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+69,0,"ram_acc_we_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+70,0,"ram_fl_din_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+71,0,"ram_fh_din_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+72,0,"ram_vol_din_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+73,0,"ram_wds_din_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+74,0,"ram_wtp_din_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+75,0,"ram_control_din_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+76,0,"ram_rts_din_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+77,0,"ram_acc_din_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+78,0,"ram_fl_dout_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+79,0,"ram_fh_dout_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+80,0,"ram_vol_dout_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+81,0,"ram_wds_dout_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+82,0,"ram_wtp_dout_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+83,0,"ram_control_dout_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+84,0,"ram_rts_dout_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+85,0,"ram_acc_dout_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+86,0,"curr_fl_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+87,0,"curr_fh_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+88,0,"curr_vol_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+89,0,"curr_wds_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+90,0,"curr_wtp_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+91,0,"curr_control_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+92,0,"curr_rts_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+93,0,"partner_control_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+94,0,"next_control_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+95,0,"prev_control_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+96,0,"zero_byte_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+97,0,"curr_osc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+98,0,"curr_osc_odd_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+99,0,"curr_osc_even_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+100,0,"partner_osc_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+101,0,"curr_wts_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+102,0,"curr_res_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+103,0,"curr_shift_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+104,0,"halt_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+105,0,"curr_mode_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+106,0,"curr_ca_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+107,0,"partner_halt_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+108,0,"partner_mode_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+109,0,"next_halt_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+110,0,"next_mode_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+111,0,"prev_halt_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+112,0,"prev_mode_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+113,0,"curr_acc_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+114,0,"curr_output_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 17,0);
    tracep->declBus(c+115,0,"loaded_wds_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+425,0,"MIXER_SUM_RESOLUTION",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+426,0,"TOP_BIT_OFFSET",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+427,0,"WINDOW_SIZE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->pushPrefix("channel_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+116+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 15,0);
    }
    tracep->popPrefix();
    tracep->pushPrefix("next_channel_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 16; ++i) {
        tracep->declBus(c+132+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 23,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+148,0,"channel_sum_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+9,0,"mono_mix_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+149,0,"next_mono_mix_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+10,0,"left_mix_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+150,0,"next_left_mix_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+11,0,"right_mix_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+151,0,"next_right_mix_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+428,0,"MODE_FREE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+429,0,"MODE_ONE_SHOT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+430,0,"MODE_SYNC_AM",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+431,0,"MODE_SWAP",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+152,0,"osc_max_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+432,0,"TICKS_PER_CYCLE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+426,0,"CYCLE_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+153,0,"cycle_timer_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+428,0,"CYCLE_RESET",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+429,0,"CYCLE_OSC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+430,0,"CYCLE_REFRESH_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+431,0,"CYCLE_REFRESH_1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+154,0,"cycle_state_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+12,0,"ready_w",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+155,0,"cycle_start_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+156,0,"clk_count_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+433,0,"OSC_STATE_COUNT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+157,0,"osc_state_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+158,0,"loaded_wds_pending_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"halt_zero_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+160,0,"host_request_pending_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"device_response_pending_r",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("acc_ram", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+425,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+418,0,"clk_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+61,0,"osc_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+69,0,"we_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+77,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->declBus(c+85,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 23,0);
    tracep->pushPrefix("osc_reg_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+162+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 23,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("control_ram", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+434,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+418,0,"clk_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+59,0,"osc_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+67,0,"we_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+75,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+83,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("osc_reg_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+194+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("fh_ram", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+434,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+418,0,"clk_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+55,0,"osc_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+63,0,"we_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+71,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+79,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("osc_reg_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+226+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("fl_ram", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+434,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+418,0,"clk_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+54,0,"osc_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+62,0,"we_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+70,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+78,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("osc_reg_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+258+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("rts_ram", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+434,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+418,0,"clk_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+60,0,"osc_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+68,0,"we_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+76,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+84,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("osc_reg_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+290+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("vol_ram", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+434,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+418,0,"clk_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+56,0,"osc_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+64,0,"we_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+72,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+80,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("osc_reg_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+322+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("wds_ram", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+434,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+418,0,"clk_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+57,0,"osc_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+65,0,"we_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+73,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+81,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("osc_reg_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+354+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("wtp_ram", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+434,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBit(c+418,0,"clk_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+58,0,"osc_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+66,0,"we_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+74,0,"data_i",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+82,0,"data_o",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->pushPrefix("osc_reg_r", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+386+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 7,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_init_top(Vdoc5503_verilog_test___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_init_top\n"); );
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vdoc5503_verilog_test___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vdoc5503_verilog_test___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vdoc5503_verilog_test___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_register(Vdoc5503_verilog_test___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_register\n"); );
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vdoc5503_verilog_test___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vdoc5503_verilog_test___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vdoc5503_verilog_test___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vdoc5503_verilog_test___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_const_0_sub_0(Vdoc5503_verilog_test___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_const_0\n"); );
    // Init
    Vdoc5503_verilog_test___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vdoc5503_verilog_test___024root*>(voidSelf);
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vdoc5503_verilog_test___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_const_0_sub_0(Vdoc5503_verilog_test___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_const_0_sub_0\n"); );
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+423,(0x337f980U),32);
    bufp->fullIData(oldp+424,(0x6d3d32U),32);
    bufp->fullIData(oldp+425,(0x18U),32);
    bufp->fullIData(oldp+426,(6U),32);
    bufp->fullIData(oldp+427,(0xfU),32);
    bufp->fullCData(oldp+428,(0U),2);
    bufp->fullCData(oldp+429,(1U),2);
    bufp->fullCData(oldp+430,(2U),2);
    bufp->fullCData(oldp+431,(3U),2);
    bufp->fullIData(oldp+432,(0x3cU),32);
    bufp->fullIData(oldp+433,(0xeU),32);
    bufp->fullIData(oldp+434,(8U),32);
}

VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_full_0_sub_0(Vdoc5503_verilog_test___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_full_0\n"); );
    // Init
    Vdoc5503_verilog_test___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vdoc5503_verilog_test___024root*>(voidSelf);
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vdoc5503_verilog_test___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vdoc5503_verilog_test___024root__trace_full_0_sub_0(Vdoc5503_verilog_test___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vdoc5503_verilog_test___024root__trace_full_0_sub_0\n"); );
    Vdoc5503_verilog_test__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelfRef.doc5503_verilog_test__DOT__reset_n));
    bufp->fullBit(oldp+2,(vlSelfRef.doc5503_verilog_test__DOT__cs_n));
    bufp->fullBit(oldp+3,(vlSelfRef.doc5503_verilog_test__DOT__we_n));
    bufp->fullCData(oldp+4,(vlSelfRef.doc5503_verilog_test__DOT__addr),8);
    bufp->fullCData(oldp+5,(vlSelfRef.doc5503_verilog_test__DOT__data_in),8);
    bufp->fullCData(oldp+6,(vlSelfRef.doc5503_verilog_test__DOT__data_out),8);
    bufp->fullSData(oldp+7,(vlSelfRef.doc5503_verilog_test__DOT__wave_address),16);
    bufp->fullBit(oldp+8,(vlSelfRef.doc5503_verilog_test__DOT__wave_rd));
    bufp->fullSData(oldp+9,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__mono_mix_r),16);
    bufp->fullSData(oldp+10,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__left_mix_r),16);
    bufp->fullSData(oldp+11,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__right_mix_r),16);
    bufp->fullBit(oldp+12,((0U != (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__cycle_state_r))));
    bufp->fullCData(oldp+13,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_en_r),8);
    bufp->fullSData(oldp+14,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[0]),16);
    bufp->fullSData(oldp+15,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[1]),16);
    bufp->fullSData(oldp+16,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[2]),16);
    bufp->fullSData(oldp+17,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[3]),16);
    bufp->fullSData(oldp+18,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[4]),16);
    bufp->fullSData(oldp+19,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[5]),16);
    bufp->fullSData(oldp+20,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[6]),16);
    bufp->fullSData(oldp+21,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[7]),16);
    bufp->fullSData(oldp+22,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[8]),16);
    bufp->fullSData(oldp+23,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[9]),16);
    bufp->fullSData(oldp+24,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[10]),16);
    bufp->fullSData(oldp+25,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[11]),16);
    bufp->fullSData(oldp+26,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[12]),16);
    bufp->fullSData(oldp+27,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[13]),16);
    bufp->fullSData(oldp+28,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[14]),16);
    bufp->fullSData(oldp+29,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_o[15]),16);
    bufp->fullCData(oldp+30,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[0]),2);
    bufp->fullCData(oldp+31,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[1]),2);
    bufp->fullCData(oldp+32,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[2]),2);
    bufp->fullCData(oldp+33,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[3]),2);
    bufp->fullCData(oldp+34,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[4]),2);
    bufp->fullCData(oldp+35,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[5]),2);
    bufp->fullCData(oldp+36,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[6]),2);
    bufp->fullCData(oldp+37,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_o[7]),2);
    bufp->fullCData(oldp+38,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_halt_r),8);
    bufp->fullCData(oldp+39,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_addr_r),8);
    bufp->fullCData(oldp+40,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_data_r),8);
    bufp->fullBit(oldp+41,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_we_n_r));
    bufp->fullBit(oldp+42,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_cs_n_r));
    bufp->fullBit(oldp+43,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_we_n_r));
    bufp->fullBit(oldp+44,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_access_r));
    bufp->fullCData(oldp+45,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_int_r),8);
    bufp->fullCData(oldp+46,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[0]),2);
    bufp->fullCData(oldp+47,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[1]),2);
    bufp->fullCData(oldp+48,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[2]),2);
    bufp->fullCData(oldp+49,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[3]),2);
    bufp->fullCData(oldp+50,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[4]),2);
    bufp->fullCData(oldp+51,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[5]),2);
    bufp->fullCData(oldp+52,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[6]),2);
    bufp->fullCData(oldp+53,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_mode_r[7]),2);
    bufp->fullCData(oldp+54,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fl_osc_r),5);
    bufp->fullCData(oldp+55,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fh_osc_r),5);
    bufp->fullCData(oldp+56,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_vol_osc_r),5);
    bufp->fullCData(oldp+57,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wds_osc_r),5);
    bufp->fullCData(oldp+58,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wtp_osc_r),5);
    bufp->fullCData(oldp+59,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_control_osc_r),5);
    bufp->fullCData(oldp+60,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_rts_osc_r),5);
    bufp->fullCData(oldp+61,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_acc_osc_r),5);
    bufp->fullBit(oldp+62,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fl_we_r));
    bufp->fullBit(oldp+63,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fh_we_r));
    bufp->fullBit(oldp+64,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_vol_we_r));
    bufp->fullBit(oldp+65,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wds_we_r));
    bufp->fullBit(oldp+66,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wtp_we_r));
    bufp->fullBit(oldp+67,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_control_we_r));
    bufp->fullBit(oldp+68,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_rts_we_r));
    bufp->fullBit(oldp+69,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_acc_we_r));
    bufp->fullCData(oldp+70,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fl_din_r),8);
    bufp->fullCData(oldp+71,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fh_din_r),8);
    bufp->fullCData(oldp+72,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_vol_din_r),8);
    bufp->fullCData(oldp+73,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wds_din_r),8);
    bufp->fullCData(oldp+74,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wtp_din_r),8);
    bufp->fullCData(oldp+75,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_control_din_r),8);
    bufp->fullCData(oldp+76,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_rts_din_r),8);
    bufp->fullIData(oldp+77,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_acc_din_r),24);
    bufp->fullCData(oldp+78,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fl_dout_w),8);
    bufp->fullCData(oldp+79,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_fh_dout_w),8);
    bufp->fullCData(oldp+80,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_vol_dout_w),8);
    bufp->fullCData(oldp+81,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wds_dout_w),8);
    bufp->fullCData(oldp+82,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_wtp_dout_w),8);
    bufp->fullCData(oldp+83,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_control_dout_w),8);
    bufp->fullCData(oldp+84,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_rts_dout_w),8);
    bufp->fullIData(oldp+85,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r
                             [vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__ram_acc_osc_r]),24);
    bufp->fullCData(oldp+86,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_fl_r),8);
    bufp->fullCData(oldp+87,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_fh_r),8);
    bufp->fullCData(oldp+88,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_vol_r),8);
    bufp->fullCData(oldp+89,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_wds_r),8);
    bufp->fullCData(oldp+90,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_wtp_r),8);
    bufp->fullCData(oldp+91,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_control_r),8);
    bufp->fullCData(oldp+92,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r),8);
    bufp->fullCData(oldp+93,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__partner_control_r),8);
    bufp->fullCData(oldp+94,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_control_r),8);
    bufp->fullCData(oldp+95,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_control_r),8);
    bufp->fullBit(oldp+96,((0U == (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_wds_r))));
    bufp->fullCData(oldp+97,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_osc_r),5);
    bufp->fullBit(oldp+98,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_osc_r))));
    bufp->fullBit(oldp+99,((1U & (~ (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_osc_r)))));
    bufp->fullCData(oldp+100,((1U ^ (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_osc_r))),5);
    bufp->fullCData(oldp+101,((7U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r) 
                                     >> 3U))),3);
    bufp->fullCData(oldp+102,((7U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r))),3);
    bufp->fullCData(oldp+103,((0x1fU & (((IData)(9U) 
                                         + (7U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r))) 
                                        - (7U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_rts_r) 
                                                 >> 3U))))),5);
    bufp->fullBit(oldp+104,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_control_r))));
    bufp->fullCData(oldp+105,((3U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_control_r) 
                                     >> 1U))),2);
    bufp->fullCData(oldp+106,((0xfU & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_control_r) 
                                       >> 4U))),4);
    bufp->fullBit(oldp+107,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__partner_control_r))));
    bufp->fullCData(oldp+108,((3U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__partner_control_r) 
                                     >> 1U))),2);
    bufp->fullBit(oldp+109,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_control_r))));
    bufp->fullCData(oldp+110,((3U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_control_r) 
                                     >> 1U))),2);
    bufp->fullBit(oldp+111,((1U & (IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_control_r))));
    bufp->fullCData(oldp+112,((3U & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__prev_control_r) 
                                     >> 1U))),2);
    bufp->fullIData(oldp+113,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_acc_r),24);
    bufp->fullIData(oldp+114,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__curr_output_r),18);
    bufp->fullCData(oldp+115,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__loaded_wds_r),8);
    bufp->fullSData(oldp+116,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[0]),16);
    bufp->fullSData(oldp+117,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[1]),16);
    bufp->fullSData(oldp+118,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[2]),16);
    bufp->fullSData(oldp+119,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[3]),16);
    bufp->fullSData(oldp+120,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[4]),16);
    bufp->fullSData(oldp+121,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[5]),16);
    bufp->fullSData(oldp+122,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[6]),16);
    bufp->fullSData(oldp+123,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[7]),16);
    bufp->fullSData(oldp+124,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[8]),16);
    bufp->fullSData(oldp+125,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[9]),16);
    bufp->fullSData(oldp+126,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[10]),16);
    bufp->fullSData(oldp+127,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[11]),16);
    bufp->fullSData(oldp+128,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[12]),16);
    bufp->fullSData(oldp+129,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[13]),16);
    bufp->fullSData(oldp+130,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[14]),16);
    bufp->fullSData(oldp+131,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_r[15]),16);
    bufp->fullIData(oldp+132,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[0]),24);
    bufp->fullIData(oldp+133,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[1]),24);
    bufp->fullIData(oldp+134,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[2]),24);
    bufp->fullIData(oldp+135,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[3]),24);
    bufp->fullIData(oldp+136,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[4]),24);
    bufp->fullIData(oldp+137,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[5]),24);
    bufp->fullIData(oldp+138,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[6]),24);
    bufp->fullIData(oldp+139,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[7]),24);
    bufp->fullIData(oldp+140,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[8]),24);
    bufp->fullIData(oldp+141,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[9]),24);
    bufp->fullIData(oldp+142,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[10]),24);
    bufp->fullIData(oldp+143,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[11]),24);
    bufp->fullIData(oldp+144,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[12]),24);
    bufp->fullIData(oldp+145,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[13]),24);
    bufp->fullIData(oldp+146,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[14]),24);
    bufp->fullIData(oldp+147,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_channel_r[15]),24);
    bufp->fullIData(oldp+148,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__channel_sum_r),24);
    bufp->fullIData(oldp+149,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_mono_mix_r),24);
    bufp->fullIData(oldp+150,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_left_mix_r),24);
    bufp->fullIData(oldp+151,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__next_right_mix_r),24);
    bufp->fullCData(oldp+152,((0x1fU & ((IData)(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_en_r) 
                                        >> 1U))),5);
    bufp->fullCData(oldp+153,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__cycle_timer_r),6);
    bufp->fullCData(oldp+154,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__cycle_state_r),2);
    bufp->fullBit(oldp+155,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__cycle_start_r));
    bufp->fullCData(oldp+156,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__clk_count_r),3);
    bufp->fullCData(oldp+157,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__osc_state_r),4);
    bufp->fullBit(oldp+158,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__loaded_wds_pending_r));
    bufp->fullBit(oldp+159,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__halt_zero_r));
    bufp->fullBit(oldp+160,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__host_request_pending_r));
    bufp->fullBit(oldp+161,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__device_response_pending_r));
    bufp->fullIData(oldp+162,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[0]),24);
    bufp->fullIData(oldp+163,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[1]),24);
    bufp->fullIData(oldp+164,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[2]),24);
    bufp->fullIData(oldp+165,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[3]),24);
    bufp->fullIData(oldp+166,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[4]),24);
    bufp->fullIData(oldp+167,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[5]),24);
    bufp->fullIData(oldp+168,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[6]),24);
    bufp->fullIData(oldp+169,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[7]),24);
    bufp->fullIData(oldp+170,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[8]),24);
    bufp->fullIData(oldp+171,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[9]),24);
    bufp->fullIData(oldp+172,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[10]),24);
    bufp->fullIData(oldp+173,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[11]),24);
    bufp->fullIData(oldp+174,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[12]),24);
    bufp->fullIData(oldp+175,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[13]),24);
    bufp->fullIData(oldp+176,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[14]),24);
    bufp->fullIData(oldp+177,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[15]),24);
    bufp->fullIData(oldp+178,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[16]),24);
    bufp->fullIData(oldp+179,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[17]),24);
    bufp->fullIData(oldp+180,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[18]),24);
    bufp->fullIData(oldp+181,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[19]),24);
    bufp->fullIData(oldp+182,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[20]),24);
    bufp->fullIData(oldp+183,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[21]),24);
    bufp->fullIData(oldp+184,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[22]),24);
    bufp->fullIData(oldp+185,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[23]),24);
    bufp->fullIData(oldp+186,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[24]),24);
    bufp->fullIData(oldp+187,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[25]),24);
    bufp->fullIData(oldp+188,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[26]),24);
    bufp->fullIData(oldp+189,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[27]),24);
    bufp->fullIData(oldp+190,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[28]),24);
    bufp->fullIData(oldp+191,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[29]),24);
    bufp->fullIData(oldp+192,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[30]),24);
    bufp->fullIData(oldp+193,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__acc_ram__DOT__osc_reg_r[31]),24);
    bufp->fullCData(oldp+194,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[0]),8);
    bufp->fullCData(oldp+195,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[1]),8);
    bufp->fullCData(oldp+196,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[2]),8);
    bufp->fullCData(oldp+197,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[3]),8);
    bufp->fullCData(oldp+198,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[4]),8);
    bufp->fullCData(oldp+199,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[5]),8);
    bufp->fullCData(oldp+200,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[6]),8);
    bufp->fullCData(oldp+201,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[7]),8);
    bufp->fullCData(oldp+202,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[8]),8);
    bufp->fullCData(oldp+203,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[9]),8);
    bufp->fullCData(oldp+204,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[10]),8);
    bufp->fullCData(oldp+205,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[11]),8);
    bufp->fullCData(oldp+206,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[12]),8);
    bufp->fullCData(oldp+207,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[13]),8);
    bufp->fullCData(oldp+208,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[14]),8);
    bufp->fullCData(oldp+209,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[15]),8);
    bufp->fullCData(oldp+210,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[16]),8);
    bufp->fullCData(oldp+211,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[17]),8);
    bufp->fullCData(oldp+212,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[18]),8);
    bufp->fullCData(oldp+213,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[19]),8);
    bufp->fullCData(oldp+214,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[20]),8);
    bufp->fullCData(oldp+215,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[21]),8);
    bufp->fullCData(oldp+216,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[22]),8);
    bufp->fullCData(oldp+217,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[23]),8);
    bufp->fullCData(oldp+218,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[24]),8);
    bufp->fullCData(oldp+219,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[25]),8);
    bufp->fullCData(oldp+220,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[26]),8);
    bufp->fullCData(oldp+221,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[27]),8);
    bufp->fullCData(oldp+222,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[28]),8);
    bufp->fullCData(oldp+223,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[29]),8);
    bufp->fullCData(oldp+224,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[30]),8);
    bufp->fullCData(oldp+225,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__control_ram__DOT__osc_reg_r[31]),8);
    bufp->fullCData(oldp+226,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[0]),8);
    bufp->fullCData(oldp+227,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[1]),8);
    bufp->fullCData(oldp+228,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[2]),8);
    bufp->fullCData(oldp+229,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[3]),8);
    bufp->fullCData(oldp+230,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[4]),8);
    bufp->fullCData(oldp+231,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[5]),8);
    bufp->fullCData(oldp+232,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[6]),8);
    bufp->fullCData(oldp+233,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[7]),8);
    bufp->fullCData(oldp+234,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[8]),8);
    bufp->fullCData(oldp+235,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[9]),8);
    bufp->fullCData(oldp+236,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[10]),8);
    bufp->fullCData(oldp+237,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[11]),8);
    bufp->fullCData(oldp+238,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[12]),8);
    bufp->fullCData(oldp+239,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[13]),8);
    bufp->fullCData(oldp+240,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[14]),8);
    bufp->fullCData(oldp+241,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[15]),8);
    bufp->fullCData(oldp+242,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[16]),8);
    bufp->fullCData(oldp+243,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[17]),8);
    bufp->fullCData(oldp+244,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[18]),8);
    bufp->fullCData(oldp+245,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[19]),8);
    bufp->fullCData(oldp+246,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[20]),8);
    bufp->fullCData(oldp+247,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[21]),8);
    bufp->fullCData(oldp+248,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[22]),8);
    bufp->fullCData(oldp+249,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[23]),8);
    bufp->fullCData(oldp+250,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[24]),8);
    bufp->fullCData(oldp+251,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[25]),8);
    bufp->fullCData(oldp+252,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[26]),8);
    bufp->fullCData(oldp+253,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[27]),8);
    bufp->fullCData(oldp+254,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[28]),8);
    bufp->fullCData(oldp+255,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[29]),8);
    bufp->fullCData(oldp+256,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[30]),8);
    bufp->fullCData(oldp+257,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fh_ram__DOT__osc_reg_r[31]),8);
    bufp->fullCData(oldp+258,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[0]),8);
    bufp->fullCData(oldp+259,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[1]),8);
    bufp->fullCData(oldp+260,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[2]),8);
    bufp->fullCData(oldp+261,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[3]),8);
    bufp->fullCData(oldp+262,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[4]),8);
    bufp->fullCData(oldp+263,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[5]),8);
    bufp->fullCData(oldp+264,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[6]),8);
    bufp->fullCData(oldp+265,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[7]),8);
    bufp->fullCData(oldp+266,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[8]),8);
    bufp->fullCData(oldp+267,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[9]),8);
    bufp->fullCData(oldp+268,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[10]),8);
    bufp->fullCData(oldp+269,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[11]),8);
    bufp->fullCData(oldp+270,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[12]),8);
    bufp->fullCData(oldp+271,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[13]),8);
    bufp->fullCData(oldp+272,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[14]),8);
    bufp->fullCData(oldp+273,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[15]),8);
    bufp->fullCData(oldp+274,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[16]),8);
    bufp->fullCData(oldp+275,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[17]),8);
    bufp->fullCData(oldp+276,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[18]),8);
    bufp->fullCData(oldp+277,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[19]),8);
    bufp->fullCData(oldp+278,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[20]),8);
    bufp->fullCData(oldp+279,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[21]),8);
    bufp->fullCData(oldp+280,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[22]),8);
    bufp->fullCData(oldp+281,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[23]),8);
    bufp->fullCData(oldp+282,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[24]),8);
    bufp->fullCData(oldp+283,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[25]),8);
    bufp->fullCData(oldp+284,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[26]),8);
    bufp->fullCData(oldp+285,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[27]),8);
    bufp->fullCData(oldp+286,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[28]),8);
    bufp->fullCData(oldp+287,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[29]),8);
    bufp->fullCData(oldp+288,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[30]),8);
    bufp->fullCData(oldp+289,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__fl_ram__DOT__osc_reg_r[31]),8);
    bufp->fullCData(oldp+290,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[0]),8);
    bufp->fullCData(oldp+291,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[1]),8);
    bufp->fullCData(oldp+292,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[2]),8);
    bufp->fullCData(oldp+293,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[3]),8);
    bufp->fullCData(oldp+294,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[4]),8);
    bufp->fullCData(oldp+295,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[5]),8);
    bufp->fullCData(oldp+296,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[6]),8);
    bufp->fullCData(oldp+297,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[7]),8);
    bufp->fullCData(oldp+298,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[8]),8);
    bufp->fullCData(oldp+299,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[9]),8);
    bufp->fullCData(oldp+300,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[10]),8);
    bufp->fullCData(oldp+301,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[11]),8);
    bufp->fullCData(oldp+302,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[12]),8);
    bufp->fullCData(oldp+303,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[13]),8);
    bufp->fullCData(oldp+304,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[14]),8);
    bufp->fullCData(oldp+305,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[15]),8);
    bufp->fullCData(oldp+306,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[16]),8);
    bufp->fullCData(oldp+307,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[17]),8);
    bufp->fullCData(oldp+308,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[18]),8);
    bufp->fullCData(oldp+309,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[19]),8);
    bufp->fullCData(oldp+310,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[20]),8);
    bufp->fullCData(oldp+311,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[21]),8);
    bufp->fullCData(oldp+312,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[22]),8);
    bufp->fullCData(oldp+313,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[23]),8);
    bufp->fullCData(oldp+314,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[24]),8);
    bufp->fullCData(oldp+315,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[25]),8);
    bufp->fullCData(oldp+316,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[26]),8);
    bufp->fullCData(oldp+317,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[27]),8);
    bufp->fullCData(oldp+318,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[28]),8);
    bufp->fullCData(oldp+319,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[29]),8);
    bufp->fullCData(oldp+320,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[30]),8);
    bufp->fullCData(oldp+321,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__rts_ram__DOT__osc_reg_r[31]),8);
    bufp->fullCData(oldp+322,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[0]),8);
    bufp->fullCData(oldp+323,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[1]),8);
    bufp->fullCData(oldp+324,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[2]),8);
    bufp->fullCData(oldp+325,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[3]),8);
    bufp->fullCData(oldp+326,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[4]),8);
    bufp->fullCData(oldp+327,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[5]),8);
    bufp->fullCData(oldp+328,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[6]),8);
    bufp->fullCData(oldp+329,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[7]),8);
    bufp->fullCData(oldp+330,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[8]),8);
    bufp->fullCData(oldp+331,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[9]),8);
    bufp->fullCData(oldp+332,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[10]),8);
    bufp->fullCData(oldp+333,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[11]),8);
    bufp->fullCData(oldp+334,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[12]),8);
    bufp->fullCData(oldp+335,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[13]),8);
    bufp->fullCData(oldp+336,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[14]),8);
    bufp->fullCData(oldp+337,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[15]),8);
    bufp->fullCData(oldp+338,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[16]),8);
    bufp->fullCData(oldp+339,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[17]),8);
    bufp->fullCData(oldp+340,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[18]),8);
    bufp->fullCData(oldp+341,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[19]),8);
    bufp->fullCData(oldp+342,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[20]),8);
    bufp->fullCData(oldp+343,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[21]),8);
    bufp->fullCData(oldp+344,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[22]),8);
    bufp->fullCData(oldp+345,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[23]),8);
    bufp->fullCData(oldp+346,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[24]),8);
    bufp->fullCData(oldp+347,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[25]),8);
    bufp->fullCData(oldp+348,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[26]),8);
    bufp->fullCData(oldp+349,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[27]),8);
    bufp->fullCData(oldp+350,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[28]),8);
    bufp->fullCData(oldp+351,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[29]),8);
    bufp->fullCData(oldp+352,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[30]),8);
    bufp->fullCData(oldp+353,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__vol_ram__DOT__osc_reg_r[31]),8);
    bufp->fullCData(oldp+354,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[0]),8);
    bufp->fullCData(oldp+355,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[1]),8);
    bufp->fullCData(oldp+356,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[2]),8);
    bufp->fullCData(oldp+357,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[3]),8);
    bufp->fullCData(oldp+358,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[4]),8);
    bufp->fullCData(oldp+359,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[5]),8);
    bufp->fullCData(oldp+360,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[6]),8);
    bufp->fullCData(oldp+361,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[7]),8);
    bufp->fullCData(oldp+362,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[8]),8);
    bufp->fullCData(oldp+363,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[9]),8);
    bufp->fullCData(oldp+364,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[10]),8);
    bufp->fullCData(oldp+365,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[11]),8);
    bufp->fullCData(oldp+366,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[12]),8);
    bufp->fullCData(oldp+367,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[13]),8);
    bufp->fullCData(oldp+368,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[14]),8);
    bufp->fullCData(oldp+369,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[15]),8);
    bufp->fullCData(oldp+370,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[16]),8);
    bufp->fullCData(oldp+371,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[17]),8);
    bufp->fullCData(oldp+372,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[18]),8);
    bufp->fullCData(oldp+373,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[19]),8);
    bufp->fullCData(oldp+374,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[20]),8);
    bufp->fullCData(oldp+375,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[21]),8);
    bufp->fullCData(oldp+376,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[22]),8);
    bufp->fullCData(oldp+377,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[23]),8);
    bufp->fullCData(oldp+378,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[24]),8);
    bufp->fullCData(oldp+379,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[25]),8);
    bufp->fullCData(oldp+380,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[26]),8);
    bufp->fullCData(oldp+381,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[27]),8);
    bufp->fullCData(oldp+382,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[28]),8);
    bufp->fullCData(oldp+383,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[29]),8);
    bufp->fullCData(oldp+384,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[30]),8);
    bufp->fullCData(oldp+385,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wds_ram__DOT__osc_reg_r[31]),8);
    bufp->fullCData(oldp+386,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[0]),8);
    bufp->fullCData(oldp+387,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[1]),8);
    bufp->fullCData(oldp+388,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[2]),8);
    bufp->fullCData(oldp+389,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[3]),8);
    bufp->fullCData(oldp+390,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[4]),8);
    bufp->fullCData(oldp+391,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[5]),8);
    bufp->fullCData(oldp+392,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[6]),8);
    bufp->fullCData(oldp+393,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[7]),8);
    bufp->fullCData(oldp+394,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[8]),8);
    bufp->fullCData(oldp+395,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[9]),8);
    bufp->fullCData(oldp+396,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[10]),8);
    bufp->fullCData(oldp+397,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[11]),8);
    bufp->fullCData(oldp+398,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[12]),8);
    bufp->fullCData(oldp+399,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[13]),8);
    bufp->fullCData(oldp+400,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[14]),8);
    bufp->fullCData(oldp+401,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[15]),8);
    bufp->fullCData(oldp+402,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[16]),8);
    bufp->fullCData(oldp+403,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[17]),8);
    bufp->fullCData(oldp+404,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[18]),8);
    bufp->fullCData(oldp+405,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[19]),8);
    bufp->fullCData(oldp+406,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[20]),8);
    bufp->fullCData(oldp+407,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[21]),8);
    bufp->fullCData(oldp+408,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[22]),8);
    bufp->fullCData(oldp+409,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[23]),8);
    bufp->fullCData(oldp+410,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[24]),8);
    bufp->fullCData(oldp+411,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[25]),8);
    bufp->fullCData(oldp+412,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[26]),8);
    bufp->fullCData(oldp+413,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[27]),8);
    bufp->fullCData(oldp+414,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[28]),8);
    bufp->fullCData(oldp+415,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[29]),8);
    bufp->fullCData(oldp+416,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[30]),8);
    bufp->fullCData(oldp+417,(vlSelfRef.doc5503_verilog_test__DOT__dut__DOT__wtp_ram__DOT__osc_reg_r[31]),8);
    bufp->fullBit(oldp+418,(vlSelfRef.doc5503_verilog_test__DOT__clk));
    bufp->fullBit(oldp+419,((0U == (7U & vlSelfRef.doc5503_verilog_test__DOT__cycle_count))));
    bufp->fullBit(oldp+420,(vlSelfRef.doc5503_verilog_test__DOT__wave_data_ready));
    bufp->fullCData(oldp+421,(vlSelfRef.doc5503_verilog_test__DOT__wave_data),8);
    bufp->fullIData(oldp+422,(vlSelfRef.doc5503_verilog_test__DOT__cycle_count),32);
}
