# GENERATED by gen_blind_sdc.sh from a2mega_dp_test.sdc — DO NOT EDIT; regenerate instead.
// Timing constraints — dp_transmitter with generated SERDES + PLL IP
// (1080p60 @ HBR x2 production rates). Copied from the timing-verified
// DisplayPort_Verilog examples/a2_mega/a2_mega_dp.sdc; instance names
// (i_mgmt_pll, i_dp) match a2mega_dp_test_top.sv.

// 50 MHz board oscillator -> gowin_mgmt_pll -> 100 MHz AUX clock
create_clock -name clk50  -period 20.000 -waveform {0 10.000} [get_ports {clk50_in}]
create_clock -name clk100 -period 10.000 -waveform {0 5.000} [get_pins {i_core/i_mgmt_pll/PLLA_inst/CLKOUT0}]

// 135 MHz TX word clock from the GTR12 quad (2.7 Gbps / 20), anchored on
// LANE2 — the bonding master for the a2mega lane pair
create_clock -name clk_sym -period 7.407 -waveform {0 3.703} [get_pins {i_core/i_dp/i_transceiver_bank/i_dp_serdes/gtr12_quad_inst0/LANE2_PCS_TX_O_FABRIC_CLK}]

// 148.5 MHz pixel clock: gowin_pixel_pll = 135 * 44/5 VCO / 8
create_clock -name clk_pix -period 6.734 -waveform {0 3.367} [get_pins {i_core/i_dp/i_pixel_pll/PLLA_inst/CLKOUT0}]

// cm_life = the GTR12 CM block's internal oscillator-derived clock.
// MEASURED on hardware 2026-08-31 (138K board, on-screen freq meter,
// diag bin b0a9c746): 60.4 MHz at power-on cooling to 60.1 MHz warm —
// a 60 MHz nominal RC-oscillator clock (210 MHz reference class, DS981
// Table 3-41: +/-5% commercial, +/-10% extended temp). The old 10 ns
// value had NO provenance ("silence TA1132") and over-constrained by
// ~66%, manufacturing a -300 ns/68-endpoint phantom family on the 138B.
// Constraint = 60 MHz * 1.10 fast-corner guard = 66 MHz -> 15.0 ns.
create_clock -name cm_life -period 15.0 [get_pins {i_core/i_dp/i_transceiver_bank/i_dp_serdes/gtr12_quad_inst0/FABRIC_CM_LIFE_CLK_O}]

// Domains exchange data only through the gray-coded CDC FIFO and 2FF
// synchronisers; no synchronous cross-domain paths exist.
set_clock_groups -asynchronous -group [get_clocks {clk50}] -group [get_clocks {clk100}] -group [get_clocks {clk_sym}] -group [get_clocks {clk_pix}] -group [get_clocks {cm_life}]

// ---------------------------------------------------------------------
// Durability margin (timing campaign round 2, 2026-09-05). Setup
// uncertainty of 0.5 ns on the fabric clocks makes the durability bar a
// property of the build: "0 setup violations" now means every path has
// at least 0.5 ns of real margin, and the timing-driven placer optimises
// against that target (diagnostic builds with a clock tightened by 1 ns
// closed clean on the 138B, so the margin is there to be found). This is
// a STRICTER requirement, not an exception; reported slack is after the
// uncertainty. Do not remove to "fix" a violation.
// ---------------------------------------------------------------------
set_clock_uncertainty 0.5 -setup -from [get_clocks {clk100}]
set_clock_uncertainty 0.5 -setup -from [get_clocks {clk_sym}]
set_clock_uncertainty 0.5 -setup -from [get_clocks {clk_pix}]
