#!/usr/bin/env bash
# Generate a2mega_dp_test_blind.sdc from a2mega_dp_test.sdc.
# The blind-sink project (a2mega_dp_test_blind.gprj) uses a thin wrapper top
# (a2mega_dp_test_blind_top -> i_core = a2mega_dp_test_top #(.BLIND(1))), so
# every hierarchical SDC object gains an i_core/ prefix; ports are unchanged.
# Re-run whenever a2mega_dp_test.sdc changes (the build does NOT do it).
set -euo pipefail
d="$(cd "$(dirname "$0")" && pwd)"
{
  echo "# GENERATED by gen_blind_sdc.sh from a2mega_dp_test.sdc — DO NOT EDIT; regenerate instead."
  sed -E 's#(get_(pins|nets|cells|regs) \{)#\1i_core/#g' "$d/a2mega_dp_test.sdc"
} > "$d/a2mega_dp_test_blind.sdc"
echo "wrote $d/a2mega_dp_test_blind.sdc"
