#!/usr/bin/env python3
"""Generate a Verilog ROM of the dp_serdes CSR write sequence.

The bitstream configures the GTR12 quad by replaying the .csr file's
upar_write_driver(addr, data) list at device configuration time. This
script converts that same list into a fabric-readable ROM so the CSR
replay FSM in transceiver_bank_gowin.v can re-execute the config-time
write sequence at runtime (common-block draw re-roll experiment,
2026-08-16). Regenerate whenever dp_serdes.csr changes:

    python3 boards/a2mega/tools/gen_csr_replay.py

Output: hdl/displayport/gowin/csr_replay_rom.svh (repo root)
"""
import re
import sys
import pathlib

root = pathlib.Path(__file__).resolve().parents[1]
# Optional argv[1] = csr path (e.g. the 138B emission); default stays the
# 60B production csr. ⚠ The output is one SHARED include consumed by
# transceiver_bank_gowin.v — regenerate it from the csr matching the die
# you are about to BUILD (stale-ROM trap, found 2026-08-21: every 138B
# build to that date carried the 60K sequence; harmless only because
# replay is on-demand).
csr_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else (
    root / "hdl/gowin/60B/dp_serdes/dp_serdes.csr")
csr = csr_path.read_text()
out = root.parents[1] / "hdl/displayport/gowin/csr_replay_rom.svh"

writes = re.findall(r"upar_write_driver\(0x([0-9a-fA-F]+),0x([0-9a-fA-F]+)\)", csr)
assert writes, "no upar_write_driver entries found"

lines = []
lines.append("// AUTO-GENERATED by boards/a2mega/tools/gen_csr_replay.py")
lines.append("// from dp_serdes.csr - DO NOT EDIT. Regenerate on IP regen.")
lines.append(f"localparam CSR_REPLAY_LEN = {len(writes)};")
lines.append("function automatic [55:0] csr_replay_rom(input [9:0] i);")
lines.append("    case (i)")
for n, (a, d) in enumerate(writes):
    lines.append(f"        10'd{n}: csr_replay_rom = {{24'h{int(a,16):06x}, 32'h{int(d,16):08x}}};")
lines.append("        default: csr_replay_rom = 56'd0;")
lines.append("    endcase")
lines.append("endfunction")
out.write_text("\n".join(lines) + "\n")
print(f"{out}: {len(writes)} writes")

# BSRAM pROM image: 512-entry hex, same {addr,data} packing as the svh
# function. mv this to the per-die _60b/_138b.hex alongside the svh.
hexout = out.with_suffix(".hex")
with hexout.open("w") as f:
    for n in range(512):
        if n < len(writes):
            a, d = writes[n]
            f.write(f"{(int(a,16) << 32) | int(d,16):014x}\n")
        else:
            f.write("0" * 14 + "\n")
print(f"{hexout}: 512-entry pROM image")
